### ISSUE TITLE
Enable formatting from `--stdin` to `stdout`

### ISSUE THREAD

**Issue by janbridley** [EbodShojaei/bake#20]
Make editors expect formatters to take input from stdin and write the output to stdout - the helix editor is one example. Would it be possible to add a `--stdin` flag (or similar) for `bake format` to enable this use case?

**Comment by EbodShojaei** [comment]
Thanks for your patience. This is available now as of the latest version 1.3.1

**Comment by janbridley** [comment]
Thank you! Here is the completed configuration for anyone curious:

```toml
# .config/helix/languages.toml
[[language]]
name = "make"
scope = "Makefile"
file-types = [{ glob = "Makefile" }]
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "mbake" , args = ["format", "--validate", "--stdin"] }
```
