### ISSUE TITLE
Create precommit hook

### ISSUE THREAD

**Issue by KindDragon** [EbodShojaei/bake#8]
Please create hook for pre-commit tool https://pre-commit.com/#new-hooks
Something like this https://github.com/astral-sh/ruff-pre-commit/blob/main/.pre-commit-hooks.yaml

**Comment by Laikulo** [comment]
Second on this. I am using the below as a workaround:
```yaml
 -  repo: local
    hooks: &mbake
      - id: mbake-format
        name: Makefile formatting (mbake)
        description: Format makefiles with Mbake
        language: python
        additional_dependencies:
          - 'mbake'
        entry: mbake format
        files: Makefile$
      - id: mbake-validate
        name: Makefile validate (mbake)
        description: Validate makefiles with Mbake
        entry: mbake validate
        files: Makefile$
        <<: *mbake
```
